### ISSUE TITLE
VR180 file format & VR toggle support?

### ISSUE THREAD

**Issue by poVoq** [R0Wi/Nextcloud-PhotoSphereViewer#1]
Great app, thanks for creating this.

Would be nice if the new VR180 format would be supported (as used by the Lenovo Daydream camera), and ideally also to have a VR toggle to look at VR and 360° photos that way.

It seems like the new v4 version of the library used is supporting some of this:
https://photo-sphere-viewer.js.org/v4/

Thanks for considering!

**Comment by R0Wi** [comment]
Thanks for your response. I'll consider upgrading soon.

**Comment by R0Wi** [comment]
Moved issue to [](https://github.com/nextcloud/files_photospheres/issues/1)
