### ISSUE TITLE
Can't display sphere when clicking on a thumbnail

### ISSUE THREAD

**Issue by Nebucatnetzer** [R0Wi/Nextcloud-PhotoSphereViewer#2]
The app works great when I open the photo from the file manager or the list view in the gallery. However when I click on the thumbnail in the gallery it opens the normal gallery viewer instead of the photo sphere viewer.
Is this fixable?

**Comment by R0Wi** [comment]
The app uses a hook for the image/jpg media type in the file manager. Could be that this hook is not enabled in the gallery app. Have to dig into it but i would say that this could only be fixed by a full integration into the gallery app.

**Comment by Nebucatnetzer** [comment]
Ah okay thanks for the information.
I'll leave the issue open for the moment.

**Comment by R0Wi** [comment]
That's ok, i'll consider a full integration of the PhotoSphere-functionallity into the gallery app for the future. So then i'm going to close the issue if an appropriate issue is created for that task :-)

**Comment by R0Wi** [comment]
Moved to [https://github.com/nextcloud/files_photospheres/issues/2]()
