### ISSUE TITLE
Add support for partial panoramas

### ISSUE THREAD

**Issue by Sanookmakmak** [R0Wi/Nextcloud-PhotoSphereViewer#3]
For example when zenith and nadir is missing or for panoramas which are stitched together of only a few images, like 120°x90°

**Comment by R0Wi** [comment]
Because the app is based on photosphere-viewer.js-library, we have to rely on the functionallity provided by this lib. 
Could this article be helpful? [https://photo-sphere-viewer.js.org/crop.html ](https://photo-sphere-viewer.js.org/crop.html)
Is this the functionallity you're looking for?

**Comment by R0Wi** [comment]
Moved to [https://github.com/nextcloud/files_photospheres/issues/3]()
