### ISSUE TITLE
Error call_user_func() when enabling app

### ISSUE THREAD

**Issue by TheNetStriker** [R0Wi/Nextcloud-PhotoSphereViewer#5]
I've noticed a strange error in the Nextcloud log. Now I found out that the error only appears if the PhotoSphereViewer is enabled. It Seems to be some kind of error when the app registers the "OCA\Files::loadAdditionalScripts" listener. Here is the full error from the log:

call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php#213

As a workarround I've changed the code in the EventDispatcher like this:

if( is_callable( $listener ) ) {
    \call_user_func($listener, $event, $eventName, $this);
}

**Comment by R0Wi** [comment]
Thanks for digging into it, @TheNetStriker . Seems like there has been a problem in the way i registered the callback. I only noticed the error, when visiting the root-folder of the actual loggedin user. Not sure why that happend but i was able to fix this by taking a look into the latest developer-documentation [here](https://docs.nextcloud.com/server/stable/developer_manual/app/view/js.html) and adapting the code. Could you verify that the error has gone by pulling the "bugfix"-branch?

**Comment by TheNetStriker** [comment]
I've just tested this and it works for me. The error is gone and panoramas are still working.
