### ISSUE TITLE
Panorama view when sharing

### ISSUE THREAD

**Issue by scootermacro** [R0Wi/Nextcloud-PhotoSphereViewer#7]
Hi, thank you for this good nextcloud-extention!

Is it possible to use the panorama-view when sharing a file for any user or public? When sharing you only get the regular image-view (I think that is maybe a similar issue like the thumbnail-issue). It would be great to have this possibility because sharing 360 degree photos!

Best regards,

Sccoter

**Comment by R0Wi** [comment]
Hi @scootermacro, thanks for your feedback. We're actually working on a new version of this app under the official nextcloud repo at https://github.com/nextcloud/files_photospheres . So @SudoHenk is going to merge his changes soon and then this will be possible.

If you're ok with that, i'll move the issue to the new repo?

**Comment by R0Wi** [comment]
Moved to https://github.com/nextcloud/files_photospheres/issues/8
